version: '3.8'
services:
  rest-api:
    build: ./microservice-rest
    ports:
      - "3000:3000"
  graphql-api:
    build: ./microservice-graphql
    ports:
      - "4000:4000"
  helper-api:
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    build: ./microservice-helper
    ports:
      - "4200:5000"
